/*
Robinhood API

Robinhood API Documentation

API version: 3.0.1
Contact: austin.millan@protonmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// OrderAction the model 'OrderAction'
type OrderAction string

// List of OrderAction
const (
	ORDER OrderAction = "order"
	STATUS OrderAction = "status"
	CANCEL OrderAction = "cancel"
	HISTORY OrderAction = "history"
)

// All allowed values of OrderAction enum
var AllowedOrderActionEnumValues = []OrderAction{
	"order",
	"status",
	"cancel",
	"history",
}

func (v *OrderAction) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OrderAction(value)
	for _, existing := range AllowedOrderActionEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid OrderAction", value)
}

// NewOrderActionFromValue returns a pointer to a valid OrderAction
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOrderActionFromValue(v string) (*OrderAction, error) {
	ev := OrderAction(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for OrderAction: valid values are %v", v, AllowedOrderActionEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v OrderAction) IsValid() bool {
	for _, existing := range AllowedOrderActionEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to OrderAction value
func (v OrderAction) Ptr() *OrderAction {
	return &v
}

type NullableOrderAction struct {
	value *OrderAction
	isSet bool
}

func (v NullableOrderAction) Get() *OrderAction {
	return v.value
}

func (v *NullableOrderAction) Set(val *OrderAction) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderAction) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderAction(val *OrderAction) *NullableOrderAction {
	return &NullableOrderAction{value: val, isSet: true}
}

func (v NullableOrderAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

